name: battleship-unit-tests

on: [push, pull_request]

jobs:
  battleship-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install g++

      - name: Compile
        run: |
          g++ -o test_battleship test_battleship.cpp 

      - name: Test
        run: |
          ./test_battleship 
